// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_listen from "./routes/api/listen.ts";
import * as $api_message from "./routes/api/message.ts";
import * as $api_move from "./routes/api/move.ts";
import * as $api_room from "./routes/api/room.ts";
import * as $api_room_object from "./routes/api/room_object.ts";
import * as $api_send from "./routes/api/send.ts";
import * as $auth_oauth2callback from "./routes/auth/oauth2callback.ts";
import * as $auth_signin from "./routes/auth/signin.ts";
import * as $auth_signout from "./routes/auth/signout.ts";
import * as $index from "./routes/index.tsx";
import * as $Room from "./islands/Room.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/listen.ts": $api_listen,
    "./routes/api/message.ts": $api_message,
    "./routes/api/move.ts": $api_move,
    "./routes/api/room.ts": $api_room,
    "./routes/api/room_object.ts": $api_room_object,
    "./routes/api/send.ts": $api_send,
    "./routes/auth/oauth2callback.ts": $auth_oauth2callback,
    "./routes/auth/signin.ts": $auth_signin,
    "./routes/auth/signout.ts": $auth_signout,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Room.tsx": $Room,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
